development:
  adapter: postgresql
  database: annotate_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: annotate_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 5
  timeout: 5000
